### ISSUE TITLE
Introduce NDRs for adding links to other vocabs

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#23]
A number of UN/CEFACT terms are defined elsewhere. In order to "fit in", we should include NDRs which define for specific elements terms such as `broaderThan`, `narrowerThan`, `equivalentProperty`, `equivalentClass`, `subClass`, `subProperty` linking to external terms. 

For example `uncl1153:Bill_of_lading_number rdfs:subPropertyOf schema:identifier` 

See also https://github.com/w3c-ccg/traceability-vocab/issues/230

**Comment by nissimsan** [comment]
We probably want to support some or all of these references. To be continued.

**Comment by nissimsan** [comment]
Encouragement to please add comments here for further discussion...

**Comment by onthebreeze** [comment]
there are a few different ideas here. 

- equivalence to external vocabularies.  We can do that (e.g. unece "party" is equivalent to schema.org "organisation"
- meaningful specialisations of uncefact generic terms (eg "rail" is a type of "transportMeans").  There are potentially two sub-types of this
  - when there exists a standard uncefact codelist that enumerates the specialised types then our NDR can just say "make a subclass for each term in the codelist"
  - when there is no term for the specialisation (eg billofLadingNumber as subtype of identifer).  this , as a technical project maybe doesnt have the authority to define new semantics.  However maybe we can define a governance mechanism for such extensions to be proposed, reviewed, and accepted/rejected.

This really does boil down to a vocabulary governance process.  I think we need to "show the way" with a more decentralised governance process

**Comment by nissimsan** [comment]
We will do this with english sentences in the section: 
https://github.com/uncefact/vocab/blob/main/docs/tech-spec.md#equivalence-vocabs
