### ISSUE TITLE
publish extra data, link to external data

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/vocab#28]
https://service.unece.org/trade/uncefact/vocabulary/unlocode-ch/#CHGVA has this info:
```
@id: unlocode-ch:CHGVA
@type: uncefact:UNLOCODE
Comment: Geneve
rdfs:comment: Geneve
rdf:value: CHGVA
```

https://locode.info/CHGVA has this info:
```
country: Switzerland (on wikipedia)
code: CH GVA
name: Genève
region: GE
functions: rail terminal, road terminal, airport, postal exchange
```

It's richer because it tells `country, region, functions` and has external link (to wikipedia).
Could you please add something like this? It's easy enough to:
- publish `country` and link it to something, eg an ISO countries list, Geonames or Wikidata 
- link LOCODEs to Geonames ADM1 (for this case, the semantic URL is https://sws.geonames.org/2660645/, which shows the human readable page https://www.geonames.org/2660645/canton-de-geneve.html)

**Comment by VladimirAlexiev** [comment]
You should also consider publishing using established ontologies. Eg with schemaorg, this could look like:
```ttl
@prefix uncefact: <https://service.unece.org/trade/uncefact/>.
@prefix unlocode: <https://service.unece.org/trade/uncefact/vocabulary/unlocode/>.
@prefix schema: <http://schema.org/>.

unlocode:CHGVA a schema:State;
  schema:name "Geneve";
  uncefact:locode "CHGVA";
  schema:containedInPlace <.../CH>;
  schema:sameAs <https://sws.geonames.org/2660645/>.

uncefact:locode rdfs:subPropertyOf schema:identifier.
```

(All LOCODEs are ADM1 administrative divisions, right?

**Comment by onthebreeze** [comment]
Well there's an interesting question here.  UNECE is the authority for locodes but they are published as csv / pdf etc not as a json-ld vocabulary. 

Our project has taken a simple mapping approach for all codes - of which locked us only one. But it loses rich semantics when the code list is a richer data set than simple name-value pairs (like locode which has port type etc)

Looks like locode.info has done a nice job - but is it authoritative? I suspect that, as an official UNCEFACT project, we should define a better vocabulary publishing model for locodes (pathos's inspired by locode.info) and basically do a proper job of it

**Comment by nissimsan** [comment]
@onthebreeze, or we could make a statement which points at locode.info and pull it from vocab on the UN server. @VladimirAlexiev I'd love your input on these considerations?

**Comment by VladimirAlexiev** [comment]
I don't know where locode.info came from, or who uses them.
If you have authoritative LOCODE info, it's better to use it: I hope it won't be a lot of work to map it.

@onthebreeze would you care to make issue(s) for other codelists that can be enriched, i.e. all of their data published as JSONLD?

**Comment by nissimsan** [comment]
I added a note about this in the NDR spec. I think that's as far as we should go; it's really not a recommendation as long as we have no idea of how it is maintained - if at all.
