### ISSUE TITLE
Itemize initial list of deliverables

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#3]
Including high level description of project goal and deliverables

**Comment by cmsdroff** [comment]
The deliverables for the project will be in 2 forms:

1. a PDF / Word document which covers the project outcomes and areas covered within scope.
2. code in the UN/CEFACT GitHub to deliver the vocabulary in a consumable format to the outside world

**Comment by nissimsan** [comment]
Nice, @cmsdroff , would you mind adding this to the document?

**Comment by cmsdroff** [comment]
@nissimsan added a PR for this and the scope #8
