### ISSUE TITLE
BIE descriptions vs prop descriptions

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/vocab#41]
https://gist.github.com/VladimirAlexiev/618a9bddd6a949b75b37e983f0220417#prop-descriptions

Some BIE Descriptions seem to be richer than prop descriptions. Eg
```ttl
cefact:Academic_Qualification.AbbreviatedName.Text a uncefact:BasicBIE ;
  rdfs:comment "The abbreviated name, expressed as text, of this academic qualification." ;
uncefact:abbreviatedName a rdf:Property ;
  rdfs:comment "An abbreviated name, expressed as text." ;
```

The BIE description could be used when the BIE is used in one term, and the term is applicable to only one class (as is the case for `uncefact:abbreviatedName`: applicable only to `uncefact:Qualification`)
1242 (or 1337?) of 1747 props satisfy this condition:
```
prefix uncefact: <https://service.unece.org/trade/uncefact/trade/uncefact/vocabulary/uncefact#> 
prefix schema: <http://schema.org/>
select * {
  ?prop uncefact:cefactElementMetadata ?bie
  filter not exists {?prop schema:domainIncludes ?dom1,?dom2 filter (?dom1 != ?dom2)}
  filter not exists {?prop uncefact:cefactElementMetadata ?bie2 filter (?bie != ?bie2)}
  ?prop rdfs:comment ?propDescr.
  ?bie rdfs:comment ?bieDescr.
} 
```

This requires further examination and unification of descriptions. Eg in the pair below:
- prop `Accreditation`: "An official recognition awarded to a person, organisation or thing, such as a building or product, to certify that a certain level of attainment has been achieved."
- BIE `Certified_Accreditation.Details`: "A certified recognition that provides evidence of a level of competency in a given area, such as certifying a level of skill in a trade."

**Comment by nissimsan** [comment]
@kshychko , at one point we listed all the applicable properties - it was pretty ugly. We're not doing this anymore, but what is actually the rule we apply now? 
Would you mind commenting, pls?

**Comment by onthebreeze** [comment]
It's an underlying incompatibility between the UN CCTS method which duplicates classes by copying abs restricting - vs RSFS which inherits and extends 

Honestly I don't know a solution to this other than to manually clean up and consequently permanently fork from the source core component library

**Comment by VladimirAlexiev** [comment]
@onthebreeze I also don't see any better way, so this would be a lot of work.

Doing all this work just to obtain a bit richer descriptions is low-priority.

However, resolving **semantic differences** between definitions should be higher priority. Eg these two seem to give somewhat different meaning to `Accreditation`?

- prop: "An official recognition awarded to a person, organisation or thing, such as a building or product, to certify that a certain level of attainment has been achieved."
- BIE "A certified recognition that provides evidence of a level of competency in a given area, such as certifying a level of skill in a trade."
