### ISSUE TITLE
Document vs Line Structure

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/vocab#44]
Document has enough props to describe also "Document Lines", which are document parts:
- `lineCountNumeric`: if it's a Document, count of lines in it
- `lineId`: if it's a DocumentLine, its line ID
- `parentLineId`: to establish a hierarchy between lines

However, there's no way to express a document hierarchy or parthood:
- Which lines comprise this Document?
- Which lines are nested under this parent line?

This leads to confusions such as

- Wrong domain? The description talks about "DocumentLine" but the domain is `Document`
```ttl
uncefact:lineStatusReason
        rdfs:comment                    "A reason, expressed as text, for the line status in this document line." ;
        schema:domainIncludes           uncefact:Document .

uncefact:lineStatusReasonCode
        rdfs:comment                    "The code specifying the line status reason for this document line." ;
        schema:domainIncludes           uncefact:Document .
```
- Wrong domain of `lineTotalBasisAmount`? Where is that "line" mentioned in the description?
  - `Tax` has 51 attributes including `basisAmount` so how can one distinguish between the two?
  - On the other hand its "sibling" prop `lineTotalAmount` has domain `MonetarySummation`
```ttl
uncefact:lineTotalBasisAmount
        rdfs:comment                    "A monetary value used as the line total basis on which this trade related tax, levy or duty is calculated." ;
        schema:domainIncludes           uncefact:Tax ;
```

**Comment by nissimsan** [comment]
This does indeed need some investigation. To my knowledge this doesn't actually like properties to standard documents. Unless I am overlooking something, I'm inclined to get rid of these properties.

**Comment by Fak3** [comment]
I was puzzled by the usefulness and semantics of those properties when I tried to model VC1 Wine import cert.
