### ISSUE TITLE
remove parasitic word "Identification" from prop names

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/vocab#48]
There are 103 props called `...Identification`:
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select * {
  ?x a rdf:Property
  filter(regex(str(?x),"Identification"))
}
```
Of them 99 are called "IdentificationId" (stuttering syndrome?)

Rename these 99 props by removing the parasitic word `...Identification..` from `...IdentificationId...`.
- Eg `uncefact:versionIdentificationId`, `bICIdentificationId` 
- These led to prop duplication, which clearly shows the parasitic nature of the long word

----

Renaming `...Indicator` to `is...` won't work well:
- eg `transportEquipmentSplitGoodsIndicator`
- cannot be named `isTransportEquipmentSplitGoods`
- could

**Comment by nissimsan** [comment]
@kshychko, I think this might actually be worthwhile cleaning these `IdentificationId` out in the code. They sure are ugly.

**Comment by nissimsan** [comment]
`Creditor_ Financial Institution. Hong Kong Bank_ Identification. Identifier`

As far as I can tell consistently, `Identification` is always paired with `Identifier`. So we could just ignore `Identification` altogether.
