### ISSUE TITLE
UN/CEFACT vocab fit in the larger linked data world

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#5]
Include architectural section positioning UN/CEFACT vocab among other vocabs. This section will require discussion and solutioning. Include discussion of: 
- specialized versus generic vocabularies
- term overrides by us
- term overrides by others

**Comment by nissimsan** [comment]
@nissimsan I'll give this a stab

**Comment by VladimirAlexiev** [comment]
@nissimsan 
How about "limit scope to core competences" as in 
"leave complex geo regions to OGC, in particular GeoSPARQL".

**Comment by nissimsan** [comment]
Precisely stuff like that. Address is my own personal favorite.  :)

**Comment by nissimsan** [comment]
@VladimirAlexiev, pls note the balance act involved: the current consensus amongst the team is that we need to "bring everything over" along with recommendations about not using parts of it, pointing elsewhere for various areas. This might seem counterproductive ("here's a gun, don't play with it"). However, actively filtering out parts of the legacy model is considered deeply controversial from a traditional point of view.

**Comment by VladimirAlexiev** [comment]
But if we recommend using GeoSPARQL, we should also show how it fits?
- "here's a gun, don't play with it"
- AND ALSO "here's a doll, here's how it fits in your truck, please play with it"

**Comment by nissimsan** [comment]
I could see this as a list of recommendations to be considered in relation to linked data implementations. And we could make references to these recommendations from the classes which we are including for completion/backwards compatibility.

**Comment by cmsdroff** [comment]
Agree as this is about linked data we should show example of how to play with other toys

**Comment by nissimsan** [comment]
We've included this sections in the bottom of the spec - closing.
