### ISSUE TITLE
Prop Name Doublons

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/vocab#51]
In addition to "IdentificationId" stuttering (#48), there are more insidious dublons in prop names that need fixing

- duplicated word: `formattedFormattedCancellationAnnouncedLaunchDateTime` : but see #52 for a whole family
- duplicated word: `referenceReferenceTypeCode`
- duplicated phrase: `documentLineDocumentLineStatusCode`

**Comment by VladimirAlexiev** [comment]
locationFunctionFunctionTypeCode -> locationFunctionType

**Comment by nissimsan** [comment]
Discussing on the call how could make an NDR rule to sort these sorts of situations out.

Best option is likely to simply remove duplicate words right next to each other.

@kshychko please run with this.

**Comment by kshychko** [comment]
The following NDR rules were implemented to produce the suggested changes in this ticket:

1. When **Object Class Term Qualifier** with **Object Class Term** or/and **Data Type Qualifier** are used to generate a property name they, are checked if the next word/phrase starts with the same character sequence.
1. Additional final check splits every property name into words and removes the duplicate word next to each other.
