### ISSUE TITLE
Include transformation code

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#7]
Add the code from the RDM2API project which transforms exported legacy (CCTS) formatted BSP model to JSON-LD.

**Comment by nissimsan** [comment]
@kshychko

**Comment by nissimsan** [comment]
Since this is java, include both source and binaries

**Comment by svanteschubert** [comment]
@kshychko 
Hi Ksenya,
Especially to understand #67 I would like to take a quick walk to the code (or its design documentation)
Is it already somewhere public available?

Thanks in advance,
Svante

**Comment by nissimsan** [comment]
@svanteschubert , the specification is here: 
https://github.com/uncefact/vocab/blob/main/docs/tech-spec.md

(... But of course nothing beats the actual code!)

**Comment by nissimsan** [comment]
@kshychko will run with this shortly.

**Comment by nissimsan** [comment]
This is done
