### ISSUE TITLE
Define a process for reporting Semantic Issues back to UN/CEFACT

### ISSUE THREAD

**Issue by cmsdroff** [uncefact/vocab#72]
We identified semantic issues that should be reported back to UN/CEFACT and most likely the library maintenance team, there are some cross overs with the API projects on these semantics.

We need to define the process with UN/CEFACT so we can raise the tickets and pass the feedback to the appropriate internal teams to make decisions or changes.

We should also know within the vocab project how we can handle these if no change is made.  

@cmsdroff to follow along with library maintenance and UN/CEFACT

**Comment by cmsdroff** [comment]
@nissimsan please assign to me and Kevin as I down have ability to do so.

**Comment by cmsdroff** [comment]
I've requested some time on the library maintenance call on the 13th April to bring this up with the library maintenance team and either get a a steer on where the process is documented or to document one.  

Will also liaise through Gerhard with the API team who also have similar points.

**Comment by nissimsan** [comment]
What is CEFACT's issue tracking system? CUE? 
Library maintenance. Excel-based?

**Comment by cmsdroff** [comment]
Here's the current changes https://github.com/uncefact/vocab/issues?q=is%3Aopen+is%3Aissue+label%3Asemantics

Maerek has offered to look into this internally

**Comment by nissimsan** [comment]
We need a paragraph to put on the semantic tickets too before closing

**Comment by cmsdroff** [comment]
Here's the feedback from library maintenance on the process, I have also some supporting documents, but suggest we define the process here in the eyes of an external participant and add to one of our deliverables on 'how to' report semantic issues.


**CCL production steps**

1.	Submission sent to Library Maintenance using template (see submission template)
2.	Editor assigned to the submission
3.	Editor performs technical assessment using technical assessment template (see it).  This involves importing the submission into Gefeg.FX, which includes the CCTS 2.01 rules.  When possible this assessment is done virtually with participation by the submitter.
4.	Once the submission is technically correct, submission is harmonized by the Library Maintenance team.  Definitions are assessed using the Definitions Boilerplate.
a.	CCs are harmonized first
b.	BIEs are next harmonized
c.	If a new qDT is submitted, that is harmonized
d.	The date, status, and any comment on every line are recorded in the spreadsheet.
5.	Harmonized CCs, BIEs, and qDTs are added to the new CCL.
6.	Spreadsheet containing the CCs and Reference BIEs for the new CCL is produced from Gefeg.FX.
7.	Library Maintenance performs Extreme QA on the CCL.  (See Extreme QA template.)  The updated CCL and Extreme QA template are posted for download by the Library Maintenance team.  During the meeting, individuals are assigned specific items to check.
a.	During this process, if errors are found, they are corrected both in the spreadsheet and in Gefeg.FX.
b.	Once the spreadsheet is completed, it is send for Validation
8.	If the Validation team finds issues, they are corrected and the spreadsheet returned to Validation.
9.	Once validation is successful, the message BIE worksheet is developed and the full CCL sent to Validation.  Once successful, the CCL is published on the UNCEFACT web page.

**Comment by cmsdroff** [comment]
@kshychko and @nissimsan correctly identified that maybe we don't propose the solution we just want to report the anomalies to library maintenance.  It is agreed that for outsiders maybe not using internal tools these changes would be quite difficult to propose a solution.

@cmsdroff to follow this back in this way

**Comment by cmsdroff** [comment]
**Todo** 

@cmsdroff to action the following:

* Collate the semantic issues that have been reported and send to library maintenance.
* Note that its sent to library maintenance 
* Comment to vladimir to show action
* Close tickets but use to comment for tracking removing from the project but showing action for reference

**Comment by cmsdroff** [comment]
The above is now done and I have reported back to Jorg who is leading the API team, @nissimsan your in copy the link for all semantic tickets (open or closed) is https://github.com/uncefact/vocab/issues?q=+is%3Aissue+label%3Asemantics+

So now I will close the `semantic` labelled issues.

@VladimirAlexiev I am closing the semantic tickets, we have agreed to report these back to UNECE to resolve internally, so rather than comment on each individually please take note that we have actioned and done something about them (reporting to the library maintenance team and other team who will need to resolve to produce a schema output)

**Comment by VladimirAlexiev** [comment]
Thanks @cmsdroff !
