### ISSUE TITLE
Add project scope section

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#8]
Establish an initial description of project scope.

**Comment by cmsdroff** [comment]
We agreed during the call that the following are out of scope:

* API and Schemas 
* Data Modelling work as we are re-using existing work rather than creating new standards or subsets of existing.

**Comment by nissimsan** [comment]
@cmsdroff  would you add to the doc, pls?

**Comment by nissimsan** [comment]
@VladimirAlexiev , formally here: 
https://github.com/uncefact/vocab/blob/main/211215%20-%203a%20JSON-LD%20web%20vocabulary%20Project%20proposal%20Approved.docx

But building upon informal work which has been going on for several years: https://github.com/edi3/edi3-json-ld-ndr (which is part of a larger https://edi3.org/ umbrella of applying new technologies to the UN/CEFACT assets)

**Comment by VladimirAlexiev** [comment]
@cmsdroff @nissimsan what do you think of https://github.com/uncefact/vocab/issues/5#issuecomment-1026404130? Comment there.

**Comment by nissimsan** [comment]
@cmsdroff , please action.

**Comment by nissimsan** [comment]
https://github.com/uncefact/vocab/blob/main/docs/tech-spec.md#scope

We did this.
