### ISSUE TITLE
Switch meetings to Thursday

### ISSUE THREAD

**Issue by nissimsan** [uncefact/vocab#97]
@onthebreeze  is asking if we can switch the meeting cadence to Thursday? Friday night is though - it's hard to not sympathize!

**Comment by kevinbish** [comment]
It is OK with me.

**Comment by cmsdroff** [comment]
good also for me

**Comment by kshychko** [comment]
good for me too

**Comment by nissimsan** [comment]
Thanks all - moving to Thursday, then!
